// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Message struct {
	Text *string `json:"text,omitempty"`
	UUID string  `json:"uuid"`
}

type Mutation struct {
}

type Query struct {
}
